### ISSUE TITLE
Initialization section fix

### ISSUE THREAD

**Issue by OlivierBBB** [Consensys/linea-specification#11]
- [x] spec fix @OlivierBBB 
  - [x] re-architecture initialization section `TX_INIT`
    - [x] split initial transfer in gas then value
    - [x] add undoing rows
    - [x] capture `misc/CCSR` / `misc/CCRS`
  - [x] update finalization section `TX_FINL`
    - [x] introduce new offset $7 < \varepsilon_{\text{revert}} < {\color{green}\varepsilon_{\text{finl}}} < \varepsilon_{\text{selfdestruct}} < \lambda$ or $\tau$
    - [x] in all cases only repay gas to sender / coinbase at offset ${\color{green}\varepsilon_{\text{finl}}}$
  - [x] introduce new `finalizationDomSubStamp` shorthands
- [x] constraints update @OlivierBBB, https://github.com/Consensys/linea-constraints/pull/517
- [ ] tracer update @lorenzogentile404

**Comment by lorenzogentile404** [comment]
@lorenzogentile404 re-implement initialization and finalization sections.

**Comment by OlivierBBB** [comment]
In the initialization section you have 2 cases:
- sender ≠ recipient

```
0th account row: sender:
balance = b  // from state
balance_new = b - gasCost

1st account row: sender:
balance = b - gasCost
balance_new = (b - gasCost) - value

2nd account row: recipient:
balance = b'  // from state
balance_new = b' + value
```

- sender = recipient

```
0th account row: sender:
balance = b  // from state
balance_new = b - gasCost

1st account row: sender:
balance = b - gasCost
balance_new = (b - gasCost) - value

2nd account row: sender:
balance = b - value // you don't get from the state
balance_new = ((b - gasCost) - value) + value
```

**Comment by OlivierBBB** [comment]
You have to add `finalizationDomSubStamps` for the finalization section.
